Add Edward Skeletal PPP
AY2122S2-CS2103T-W14-3/tp pull request #18
Opened 2022-03-04 10:31 UTC by ThePrevailingOne

2022-03-04 14:29 UTC, Graphcalibur requested changes

2022-03-04 14:29 UTC, Graphcalibur commented on docs/AboutUs.md
> -[[github](http://github.com/johndoe)] [[portfolio](team/johndoe.md)]
The portfolio link I believe should be kept as it is supposed to link to the PPP

2022-03-09 01:47 UTC, ThePrevailingOne commented
Can check if the update is already right

2022-03-09 03:21 UTC, albertsutz requested changes

2022-03-09 03:21 UTC, albertsutz commented on docs/team/theprevailingone.md
> +  * Credits: *{mention here if you reused any code/ideas from elsewhere or if a third-party library is heavily used in the feature so that a reader can make a more accurate judgement of how much effo
Can remove this first. Every other things looks good!

2022-03-09 04:14 UTC, albertsutz approved these changes

2022-03-09 04:51 UTC, Graphcalibur approved these changes
LGTM!

2022-03-09 04:53 UTC, merged