Add Use cases to Developer Guide
AY2122S2-CS2103T-W14-3/tp pull request #33
Opened 2022-03-09 03:07 UTC by ThePrevailingOne

2022-03-09 05:02 UTC, Graphcalibur requested changes
I think that more use cases should be added.
Also, should we add more terms to the glossary?

2022-03-11 10:38 UTC, ThePrevailingOne commented on docs/DeveloperGuide.md
>  (For all use cases below, the **System** is the `AddressBook` and the **Actor** is the `user`, unless specified otherwise)
Already changed 👍

2022-03-11 12:46 UTC, Graphcalibur requested changes

2022-03-11 12:46 UTC, Graphcalibur commented on docs/DeveloperGuide.md
> +3.  InternBuddy assign a tag to the company with the company name as the tag
> assign a tag to the company with the company name as the tag

What does this mean?

2022-03-11 13:28 UTC, ThePrevailingOne commented
> > assign a tag to the company with the company name as the tag
>
> What does this mean? 

since currently the company doesn't have any relation to the tag, the tag used by event and contact person is not associated to the company if I don't assign it.

2022-03-11 13:52 UTC, Graphcalibur approved these changes
LGTM then!

2022-03-11 14:29 UTC, merged