Create Generic Entry class and UniqueEntryList
AY2122S2-CS2103T-W14-3/tp pull request #39
Opened 2022-03-11 08:10 UTC by Graphcalibur

Companies, Events, and Persons all have some common attributes and methods (e.g. name, tags, isSameEntry()).

Creating a generic Entry class and converting UniquePersonList into UniqueEntryList that can hold any child class of Entry allows Companies and Events to be added into the existing infrastructure while reusing as much of the existing code as possible.

Let's
* create a Entry class that Person inherits from and contains the aforementioned common attributes and methods
* convert UniquePersonList into a UniqueEntryList that can hold any child class of Entry.
* convert the Person-specific exceptions into general Entry exceptions

2022-03-13 16:41 UTC, albertsutz requested changes
I feel that there can be some slight changes 

1. We will have 3 big children of entries: Event, Person, and Company, therefore

- I think we should package each accordingly
- e.g. Person.java should be in seedu.address.model.entry.person
- This also makes it easier to organize the attributes that is unique to a Person, which is the phone, email, and address. (Phone.java, Email.java. and Address.java should also be in the person folder)

I think that following the above recommendation can help us organize all three types of entries better.

2022-03-13 16:41 UTC, albertsutz commented on src/main/java/seedu/address/model/entry/UniqueEntryList.java
> + * A list of persons that enforces uniqueness between its elements and does not allow nulls.
A List of person should be a list of Entry

2022-03-13 16:41 UTC, albertsutz commented on src/main/java/seedu/address/model/entry/UniqueEntryList.java
> +     * The person must not already exist in the list.
Should change person to entry

2022-03-13 16:41 UTC, albertsutz commented on src/main/java/seedu/address/model/entry/exceptions/DuplicateEntryException.java
>          super("Operation would result in duplicate persons");
error message should be duplicate entry. the Javadocs should also be changed.

2022-03-14 06:32 UTC, Graphcalibur commented
I think that's a good way of organizing the code but I also think it's something that should be done once we start implementing Companies/Events in a later PR.

I've also fixed the various instances of comments and messages still referring to "Persons" instead of "Entries".

2022-03-14 12:04 UTC, mradhyaf reviewed
Looks good I think.

2022-03-14 12:43 UTC, albertsutz approved these changes

2022-03-14 12:43 UTC, merged